### ISSUE TITLE
小米11 pro 测试成功！

### ISSUE THREAD

**Issue by 498110811** [tanz3/kernel_xiaomi_sm8350-miui#2]
小米11 pro 测试成功！ 目前出现的问题是 指纹和NFC无效 需要修复下

**Comment by tanz3** [comment]
请提供MIUI 版本和当前版本的/proc/config.gz文件，谢谢

**Comment by 498110811** [comment]
miui14.0.23.1.30   发现的问题有 nfc和指纹不能使用 震动声音不对 /proc/config.gz 因为我已经回退了 原版boot 所以还无法提供

**Comment by 498110811** [comment]
我是使用的clang14编译的  kernelsu不支持overlayfs
